# Google OAuth 2.0 Configuration
# DO NOT commit this file to Git - add to .gitignore
google.client.id=1074465622889-blplqio1k0dggnpffqc9v0oe4p8n5te0.apps.googleusercontent.com
google.client.secret=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
google.redirect.uri=http://localhost:8888/callback
